---
name: Node.js application
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    name: Singular Id
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: List directory contents
        run: ls -al
      - name: Go to backend
        run: cd backend
      - name: Install dependencies
        run: npm install
      - name: Go to root
        run: cd ..
      - name: Build Docker image
        run: >
          docker build -t docker push vaibhavrawat/singular-id:latest .

          docker tag vaibhavrawat/singular-id:latest vaibhavrawat/singular-id:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: |
            vaibhavrawat/singular-id:latest
            vaibhavrawat/singular-id:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
